inputs:
  src_path:
    required: true
  host:
    required: true
  dst_path:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        set -x
        dir_arg=""
        if [ -d "${{ inputs.src_path }}" ]; then
          dir_arg="-r"
        fi
        parent_path=$(dirname ${{ inputs.dst_path }})
        ssh ${{ inputs.host }} mkdir -p parent_path
        scp ${dir_arg} ${{ inputs.src_path }} ${{ inputs.host }}:~/${{ inputs.dst_path }}
      shell: bash
