inputs:
  name:
    description: 'Placeholder'
    default: 'Placeholder'
runs:
  using: "composite"
  steps:
    - run: |
        rm -rf build/third_party
        bash ci/build/clean.sh
      shell: bash
