import oneflow.framework.python_callback as python_callback
import oneflow.eager.interpreter_callback as interpreter_callback
import oneflow._oneflow_internal
python_callback.interpreter_callback = interpreter_callback