import oneflow._oneflow_internal
import oneflow.eager.interpreter_callback as interpreter_callback
import oneflow.framework.python_callback as python_callback

python_callback.interpreter_callback = interpreter_callback
