#ifndef ONEFLOW_IR_ONEFLOW_JIT_INCLUDE_ONEFLOW_DIALECT_JIT_IR_ONEFLOWJITOPS_H_
#define ONEFLOW_IR_ONEFLOW_JIT_INCLUDE_ONEFLOW_DIALECT_JIT_IR_ONEFLOWJITOPS_H_
#include "mlir/IR/OpDefinition.h"
#include "OneFlow/Dialect/JIT/IR/OneFlowJITInterfaces.h.inc"
#define GET_OP_CLASSES
#include "OneFlow/Dialect/JIT/IR/OneFlowJITOps.h.inc"
#endif  // ONEFLOW_IR_ONEFLOW_JIT_INCLUDE_ONEFLOW_DIALECT_JIT_IR_ONEFLOWJITOPS_H_
