pull_request_rules:
  - name: automatic update for PR with label “automerge“
    conditions:
      - "#approved-reviews-by>=2"
      - -conflict # skip conflicts
      - -draft # skip draft PRs
      - label="automerge"
    actions:
      update:
      request_reviews:
        users:
          - oneflow-ci-bot
