inputs:
  src_path:
    required: true
  oss_dst_path:
    required: true
  oss_access_key_id:
    required: true
  oss_access_key_secret:
    required: true
  upload_core:
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        if [ -z "$OSS_ACCESS_KEY_ID" ]
        then
          exit 0
        fi
        if [ ! -f "$HOME/ossutil64" ]; then
          curl http://gosspublic.alicdn.com/ossutil/1.7.15/ossutil64 -o $HOME/ossutil64
        fi
        chmod 755 $HOME/ossutil64
        $HOME/ossutil64 config -e oss-cn-beijing.aliyuncs.com -i ${{ inputs.oss_access_key_id }} -k ${{ inputs.oss_access_key_secret }}  -L EN -c $HOME/.ossutilconfig
        dir_arg=""
        if [ -d "${{ inputs.src_path }}" ]; then
          dir_arg="--recursive"
        fi
        upload_core_arg=""
        if [ "${{ inputs.upload_core }}" == "true" ]; then
            echo "will upload core files"
        else
            upload_core_arg+='--exclude "core*"'
        fi
        set -x
        $HOME/ossutil64 cp --disable-ignore-error --update ${dir_arg} ${upload_core_arg} ${{ inputs.src_path }} ${{ inputs.oss_dst_path }}
      shell: bash
      env:
        OSS_ACCESS_KEY_ID: ${{ inputs.oss_access_key_id }}
        OSS_ACCESS_KEY_SECRET: ${{ inputs.oss_access_key_secret }}
