/*
Copyright 2020 The OneFlow Authors. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "cutlass/library/src/conv2d_operation.h"
#include "cutlass/library/src/library_internal.h"

#include "oneflow/user/kernels/cutlass/external_singleton.h"

///////////////////////////////////////////////////////////////////////////////////////////////////

// Conv2dFprop Optimized kernel instance "cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc"
template<int Alignment, int AlignmentC>
using cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_base =
    typename cutlass::conv::kernel::DefaultConv2dFprop<
        int8_t, cutlass::layout::TensorNHWC, int8_t, cutlass::layout::TensorNHWC, int32_t,
        cutlass::layout::TensorNHWC, int32_t, cutlass::arch::OpClassTensorOp, cutlass::arch::Sm75,
        cutlass::gemm::GemmShape<64, 32, 32>, cutlass::gemm::GemmShape<32, 32, 32>,
        cutlass::gemm::GemmShape<8, 8, 16>,
        cutlass::epilogue::thread::LinearCombination<int32_t, AlignmentC, int32_t, int32_t>,
        cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<
            4>,  // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
        2, cutlass::arch::OpMultiplyAddSaturate, cutlass::conv::IteratorAlgorithm::kOptimized,
        cutlass::conv::StrideSupport::kStrided, Alignment, Alignment>::Kernel;

// Derived class
template<int Alignment, int AlignmentC>
struct cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc
    : public cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_base<Alignment, AlignmentC> {
};

///////////////////////////////////////////////////////////////////////////////////////////////////

template<int Alignment, int AlignmentC>
using Operation_cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc =
    cutlass::conv::device::ImplicitGemmConvolution<
        cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc<Alignment, AlignmentC>>;

namespace cutlass {
namespace library {

// Initialize all instances
ONEFLOW_CUTLASS_MANIFEST(manifest) {
  manifest.append(new cutlass::library::Conv2dOperation<
                  Operation_cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc<1, 1>>(
      "cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_align1"));
  manifest.append(new cutlass::library::Conv2dOperation<
                  Operation_cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc<2, 2>>(
      "cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_align2"));
  manifest.append(new cutlass::library::Conv2dOperation<
                  Operation_cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc<4, 4>>(
      "cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_align4"));
  manifest.append(new cutlass::library::Conv2dOperation<
                  Operation_cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc<8, 4>>(
      "cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_align8"));
  manifest.append(new cutlass::library::Conv2dOperation<
                  Operation_cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc<16, 4>>(
      "cutlass_tensorop_i8816fprop_optimized_s8_64x32_32x2_nhwc_align16"));
}

///////////////////////////////////////////////////////////////////////////////////////////////////

}  // namespace library
}  // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////
