FROM nvidia/cuda:9.1-cudnn7-runtime-centos7
LABEL Author="xxmyjk <xxmyj.k@gmail.com>"

USER root

RUN yum install -y epel-release
RUN yum update -y && yum install -y \
    cmake3 \
    make \
    libibverbs \
    rdma-core-devel \
    libgsasl

ADD ./bin/oneflow /opt/bin/

RUN yum clean -y all && rm -rf /var/cache/yum

ENV LD_LIBRARY_PATH="/mnt/lib:/usr/lib64:${LD_LIBRARY_PATH}"
ENV PATH="${LD_LIBRARY_PATH}:/opt/bin:${PATH}"

WORKDIR /opt
