from oneflow.compatible.single_client.framework.sysconfig import get_include
from oneflow.compatible.single_client.framework.sysconfig import get_lib
from oneflow.compatible.single_client.framework.sysconfig import get_compile_flags
from oneflow.compatible.single_client.framework.sysconfig import get_link_flags
from oneflow.compatible.single_client.framework.sysconfig import with_cuda
from oneflow.compatible.single_client.framework.sysconfig import with_xla
from oneflow.compatible.single_client.framework.sysconfig import has_rpc_backend_grpc
from oneflow.compatible.single_client.framework.sysconfig import has_rpc_backend_local