# See here for image contents: https://github.com/Oneflow-Inc/docker-images/blob/main/oneflow/Dockerfile
# [Choice] llvm12 llvm13 cuda11.1
ARG VARIANT="llvm13"
FROM registry.cn-beijing.aliyuncs.com/oneflow/devcontainer:${VARIANT}
