inputs:
  name:
    description: 'Placeholder'
    default: 'Placeholder'
runs:
  using: "composite"
  steps:
    - run: |
        docker run --rm -v $PWD:/p -w /p busybox chmod -R o+w .
        rm -rf build/third_party
        bash ci/build/clean.sh
      shell: bash
