inputs:
  name:
    description: 'Placeholder'
    default: 'Placeholder'
runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install black==19.10b0
        python3 ci/check/run_license_format.py -i oneflow -c
        python3 ci/check/run_clang_format.py --clang_format_binary clang-format --source_dir oneflow
        python3 ci/check/run_py_format.py --source_dir $PWD
      shell: bash
