inputs:
    tmp_dir:
      description: 'tmp dir in home'
      default: 'ci-tmp'
    cuda_version:
      description: 'cuda_version'
      default: '10.2'
    python_version:
      description: 'python_version'
      default: '3.6'
    extra_flags:
      description: 'flags like --xla'
      default: ''
runs:
  using: "composite"
  steps:
    - run: |
        tmp_dir="$HOME/${{ inputs.tmp_dir }}"
        docker run --rm \
            -v $tmp_dir:/p \
            -w $tmp_dir:/p busybox rm -rf /p/wheelhouse

        python3 docker/package/manylinux/build_wheel.py \
            --cuda_version=${{ inputs.cuda_version }}" \
            --python_version=${{ inputs.python_version }}" \
            --use_tuna \
            --use_system_proxy --use_aliyun_mirror \
            --wheel_house_dir=${tmp_dir}/wheelhouse \
            --oneflow_src_dir=${PWD} \
            ${{ inputs.extra_flags }}

        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        timestamp=$(date '+%Y.%m.%d-%H.%M.%S')
        dir=${{ github.event.pull_request.number }}/${timestamp}-${git_hash}-cuda
        for filename in ${tmp_dir}/wheelhouse/*.whl; do
            $HOME/ossutil64 cp $filename oss://oneflow-static/staging/pr/${dir}/`basename $filename`
        done
      shell: bash
