#ifndef ONEFLOW_CORE_COMMON_PREPROCESSOR_H_
#define ONEFLOW_CORE_COMMON_PREPROCESSOR_H_

#include "oneflow/core/common/preprocessor_internal.h"

#define OF_PP_CAT(a, b) OF_PP_INTERNAL_CAT(a, b)

#define OF_PP_JOIN(glue, ...) OF_PP_INTERNAL_JOIN(glue, __VA_ARGS__)

#define OF_PP_STRINGIZE(x) OF_PP_INTERNAL_STRINGIZE(x)

#define OF_PP_VARIADIC_SIZE(...) OF_PP_INTERNAL_VARIADIC_SIZE(__VA_ARGS__)

#define OF_PP_PAIR_FIRST(pair) OF_PP_INTERNAL_PAIR_FIRST(pair)

#define OF_PP_PAIR_SECOND(pair) OF_PP_INTERNAL_PAIR_SECOND(pair)

#define OF_PP_TUPLE_SIZE(t) OF_PP_INTERNAL_TUPLE_SIZE(t)

#define OF_PP_TUPLE_ELEM(n, t) OF_PP_INTERNAL_TUPLE_ELEM(n, t)

#define OF_PP_TUPLE_PUSH_FRONT(t, x) OF_PP_INTERNAL_TUPLE_PUSH_FRONT(t, x)

#define OF_PP_MAKE_TUPLE_SEQ(...) OF_PP_INTERNAL_MAKE_TUPLE_SEQ(__VA_ARGS__)

#define OF_PP_FOR_EACH_TUPLE(macro, seq) \
  OF_PP_INTERNAL_FOR_EACH_TUPLE(macro, seq)

#define OF_PP_SEQ_MAP(macro, seq) \
  OF_PP_SEQ_PRODUCT_FOR_EACH_TUPLE(OF_PP_I_SEQ_MAP_DO_EACH, (macro), seq)
#define OF_PP_I_SEQ_MAP_DO_EACH(macro, elem) (macro(elem))

#define OF_PP_SEQ_PRODUCT_FOR_EACH_TUPLE(macro, ...) \
  OF_PP_INTERNAL_SEQ_PRODUCT_FOR_EACH_TUPLE(macro, __VA_ARGS__)

#define OF_PP_SEQ_SIZE(seq) OF_PP_INTERNAL_SEQ_SIZE(seq)

#define OF_PP_FORCE(...) OF_PP_TUPLE2VARADIC(OF_PP_CAT((__VA_ARGS__), ))
#define OF_PP_TUPLE2VARADIC(t) OF_PP_TUPLE2VARADIC_I(t)
#define OF_PP_TUPLE2VARADIC_I(t) OF_PP_TUPLE2VARADIC_II t
#define OF_PP_TUPLE2VARADIC_II(...) __VA_ARGS__

#endif  // ONEFLOW_CORE_COMMON_PREPROCESSOR_H_
