#ifndef ONEFLOW_CORE_COMMON_PREPROCESSOR_H_
#define ONEFLOW_CORE_COMMON_PREPROCESSOR_H_

#include "oneflow/core/common/preprocessor_internal.h"

#define OF_PP_CAT OF_PP_INTERNAL_CAT

#define OF_PP_STRINGIZE OF_PP_INTERNAL_STRINGIZE

#define OF_PP_MAKE_TUPLE_SEQ OF_PP_INTERNAL_MAKE_TUPLE_SEQ

#define OF_PP_FOR_EACH_TUPLE OF_PP_INTERNAL_FOR_EACH_TUPLE

#define OF_PP_SEQ_PRODUCT_FOR_EACH_TUPLE \
  OF_PP_INTERNAL_SEQ_PRODUCT_FOR_EACH_TUPLE

#define OF_PP_FIRST_ARG OF_PP_INTERNAL_FIRST_ARG
#define OF_PP_SECOND_ARG OF_PP_INTERNAL_SECOND_ARG

#endif  // ONEFLOW_CORE_COMMON_PREPROCESSOR_H_
