function(STR_ENDSWITH str postfix IS_CORRECT)
  set(${IS_CORRECT})
  string(LENGTH ${str} str_length)
  string(LENGTH ${postfix} postfix_length)
  math(EXPR begin_pos ${str_length}-${postfix_length})
  if((${begin_pos} GREATER 0) OR (${begin_pos} EQUAL 0))
    string(SUBSTRING ${str} ${begin_pos} ${postfix_length} str_postfix)
    string(COMPARE EQUAL ${str_postfix} ${postfix} ${IS_CORRECT})
  endif()
  set(${IS_CORRECT} ${${IS_CORRECT}} PARENT_SCOPE)
endfunction()

function(ONEFLOW_SOURCE_GROUP group)
  cmake_parse_arguments(ONEFLOW_SOURCE_GROUP "" "" "GLOB;GLOB_RECURSE" ${ARGN})
  if(ONEFLOW_SOURCE_GROUP_GLOB)
    file(GLOB srcs1 ${ONEFLOW_SOURCE_GROUP_GLOB})
    source_group(${group} FILES ${srcs1})
  endif()

  if(ONEFLOW_SOURCE_GROUP_GLOB_RECURSE)
    file(GLOB_RECURSE srcs2 ${ONEFLOW_SOURCE_GROUP_GLOB_RECURSE})
    source_group(${group} FILES ${srcs2})
  endif()
endfunction()

MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()
