name: "Upload via ssh"
description: ""
inputs:
  src_path:
    required: true
    description: ""
  dst_host:
    required: true
    description: ""
  dst_path:
    required: true
    description: ""
runs:
  using: "composite"
  steps:
    - name: Create parent directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ inputs.dst_host }} mkdir -p $(dirname ${{ inputs.dst_path }})
      shell: bash
    - name: Copy files
      run: |
        set -x
        scp -r ${{ inputs.src_path }} ${{ inputs.dst_host }}:${{ inputs.dst_path }}
      shell: bash
