if(DEFINED ENV{ONELFOW_INSTALL_PREFIX})
  set(ONELFOW_INSTALL_PREFIX $ENV{ONELFOW_INSTALL_PREFIX})
else()
  get_filename_component(CMAKE_CURRENT_LIST_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
  get_filename_component(ONELFOW_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
endif()

set(ONEFLOW_INCLUDE_DIRS ${ONELFOW_INSTALL_PREFIX}/include)

find_library(ONEFLOW_LIBRARY NAMES oneflow PATHS ${ONELFOW_INSTALL_PREFIX}/lib REQUIRED)

set(ONEFLOW_LIBRARYS ${ONEFLOW_LIBRARY})
