function(STR_ENDSWITH str postfix IS_CORRECT)
  set(${IS_CORRECT})
  string(LENGTH ${str} str_length)
  string(LENGTH ${postfix} postfix_length)
  math(EXPR begin_pos ${str_length}-${postfix_length})
  if((${begin_pos} GREATER 0) OR (${begin_pos} EQUAL 0))
    string(SUBSTRING ${str} ${begin_pos} ${postfix_length} str_postfix)
    string(COMPARE EQUAL ${str_postfix} ${postfix} ${IS_CORRECT})
  endif()
  set(${IS_CORRECT} ${${IS_CORRECT}} PARENT_SCOPE)
endfunction()
