#define MLU_PRIMITIVE_ALL_TYPE_SEQ \
  CPU_PRIMITIVE_BOOL_TYPE_SEQ      \
  CPU_PRIMITIVE_INT8_TYPE_SEQ      \
  CPU_PRIMITIVE_UINT8_TYPE_SEQ     \
  CPU_PRIMITIVE_INT32_TYPE_SEQ     \
  CPU_PRIMITIVE_UINT32_TYPE_SEQ    \
  CPU_PRIMITIVE_INT64_TYPE_SEQ     \
  CPU_PRIMITIVE_UINT64_TYPE_SEQ    \
  CPU_PRIMITIVE_FLOAT_TYPE_SEQ     \
  CPU_PRIMITIVE_FLOAT16_TYPE_SEQ
